static inline int mandel(float c_re, float c_im, int count) {
    float z_re = c_re, z_im = c_im;
    int i;
    for (i = 0; i < count; ++i) {
        if (z_re * z_re + z_im * z_im > 4.f)
            break;
        float new_re = z_re*z_re - z_im*z_im;
        float new_im = 2.f * z_re * z_im;
        z_re = c_re + new_re;
        z_im = c_im + new_im;
    }
    return i;
}

export void mandelbrot_ispc(uniform float x0, uniform float y0,
                            uniform float x1, uniform float y1,
                            uniform int width, uniform int height,
                            uniform int maxIterations,
                            uniform int output[]) {
    uniform float dx = (x1 - x0) / width;
    uniform float dy = (y1 - y0) / height;
    foreach (j = 0 ... height, i = 0 ... width) {
        float x = x0 + i * dx;
        float y = y0 + j * dy;
        output[j * width + i] = mandel(x, y, maxIterations);
    }
}

task void mandelbrot_ispc_task(uniform float x0, uniform float y0,
                               uniform float x1, uniform float y1,
                               uniform int width, uniform int height,
                               uniform int rowsPerTask,
                               uniform int maxIterations,
                               uniform int output[]) {
    uniform int ystart = taskIndex * rowsPerTask;
    uniform int yend = ystart + rowsPerTask;
    if (yend > height)
        yend = height;
    if (ystart >= height)
        return;

    uniform float dx = (x1 - x0) / width;
    uniform float dy = (y1 - y0) / height;
    foreach (j = ystart ... yend, i = 0 ... width) {
        float x = x0 + i * dx;
        float y = y0 + j * dy;
        output[j * width + i] = mandel(x, y, maxIterations);
    }
}

export void mandelbrot_ispc_withtasks(uniform float x0, uniform float y0,
                                      uniform float x1, uniform float y1,
                                      uniform int width, uniform int height,
                                      uniform int maxIterations,
                                      uniform int taskCount,
                                      uniform int output[]) {
    if (taskCount < 1)
        taskCount = 1;
    uniform int rowsPerTask = (height + taskCount - 1) / taskCount;
    launch[taskCount] mandelbrot_ispc_task(x0, y0, x1, y1,
                                           width, height, rowsPerTask,
                                           maxIterations, output);
}
